name: Generate GitHub Metrics

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          config_display: large
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_stars: yes
          plugin_stars_limit: 4
          output_action: commit
          committer_message: "chore: update GitHub profile metrics"
          committer_branch: metrics
